#A per AS rate limit filter for local and outside traffic
[packetRateLimit]
    [packetRateLimit.LocalConfig]
    NumOfClients = 1
    Interval = "1s"
    MaxCount = 9

    [packetRateLimit.OutsideConfig]
    NumOfClients = 8
    Interval = "1s"
    MaxCount = 50
