[IntervalRequestLimiting]
    [IntervalRequestLimiting.External]
    NumOfClients = 16
    Interval = "1s"
    MaxCount = 65535

[RequestConfigs]
    [RequestConfigs.TRCRequest]
    ExternalRateLimit = "Interval"

    [RequestConfigs.ChainRequest]
    ExternalRateLimit = "Interval"
