[IntervalRequestLimiting]
    [IntervalRequestLimiting.External]
    NumOfClients = 16384
    Interval = "1s"
    MaxCount = 255

[RequestConfigs]
    [RequestConfigs.TRCRequest]
    ExternalRateLimit = "Interval"

    [RequestConfigs.ChainRequest]
    ExternalRateLimit = "Interval"
